site_name: purrpalette
repo_url: https://github.com/JosephBARBIERDARNAL/purrpalette
site_author: Joseph Barbier
nav:
  - Home: index.md
  - Quick start: quick_start.md
theme:
  name: readthedocs
  user_color_mode_toggle: true
extra_css:
  - style.css
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_full_path: false
            heading_level: 3
            separate_signature: true
            show_if_no_docstring: false
            filters: []